# Generated by Django 3.2 on 2022-02-07 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(default=0)),
                ('is_cash', models.BooleanField()),
                ('is_saving_goal', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active_saving_goal', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('accomplished_date', models.DateField(blank=True, null=True)),
                ('goal_value', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('income', models.BooleanField(blank=True, null=True)),
                ('master_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='financeAwareness.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('income', 'Przychód'), ('expense', 'Wydatek'), ('planned', 'Zaplanowana'), ('recurringExpense', 'Stały wydatek'), ('recurringIncome', 'Stały przychód'), ('transfer', 'Transfer')], max_length=20)),
                ('reccuring_type', models.CharField(choices=[('month', 'Miesiąc'), ('quarter', 'Kwartał'), ('year', 'Rok'), ('week', 'tydzień')], max_length=20, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeAwareness.account')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='financeAwareness.Tag')),
                ('transfer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='financeAwareness.account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_value', models.FloatField()),
                ('is_planned', models.BooleanField(blank=True, default=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='financeAwareness.category')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financeAwareness.transaction')),
            ],
            options={
                'db_table': 'transactionItem',
            },
        ),
    ]
