# Generated by Django 3.2 on 2022-01-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('is_finished', models.BooleanField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryID',
            new_name='category_id',
        ),
    ]
