# Generated by Django 3.2 on 2022-02-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='income',
            new_name='is_income',
        ),
    ]
