# Generated by Django 3.2 on 2022-03-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0002_rename_income_category_is_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-accomplished_date',)},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reccuring_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_type',
            field=models.CharField(choices=[('month', 'Miesiąc'), ('quarter', 'Kwartał'), ('year', 'Rok'), ('week', 'Tydzień')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Przychód'), ('expense', 'Wydatek'), ('planned', 'Zaplanowana'), ('recurringExpense', 'Stały wydatek'), ('recurringIncome', 'Stały przychód'), ('transfer', 'Transfer')], max_length=16),
        ),
    ]
