# Generated by Django 3.2 on 2022-01-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0002_auto_20220120_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
    ]
