# Generated by Django 3.2 on 2022-01-21 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0003_alter_transaction_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('transaction_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('is_planned', models.BooleanField(default=False)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeAwareness.transaction')),
            ],
        ),
    ]
