# Generated by Django 3.2 on 2022-01-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0004_transactionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
    ]
