# Generated by Django 3.2 on 2022-01-21 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeAwareness', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='auth.user'),
            preserve_default=False,
        ),
    ]
