# Generated by Django 3.2 on 2022-01-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0011_auto_20220122_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
