# Generated by Django 3.2 on 2022-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0013_auto_20220122_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='is_planned',
            field=models.BooleanField(),
        ),
    ]
