# Generated by Django 3.2 on 2022-01-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0016_alter_account_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='income',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
