# Generated by Django 3.2 on 2022-01-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0017_category_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='financeAwareness.category'),
        ),
    ]
