# Generated by Django 3.2 on 2022-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0018_alter_transactionitem_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accomplished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='goal_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_saving_goal',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
