# Generated by Django 3.2 on 2022-01-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0019_auto_20220124_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_saving_goal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
