# Generated by Django 3.2 on 2022-01-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0023_transfer_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='recurringtransaction',
            table='recurringTransaction',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='transactionitem',
            table='transactionItem',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='transfer',
        ),
    ]
