# Generated by Django 3.2 on 2022-01-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0024_auto_20220124_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active_saving_goal',
            field=models.BooleanField(default=False),
        ),
    ]
