# Generated by Django 3.2 on 2022-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0025_account_is_active_saving_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_saving_goal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
