# Generated by Django 3.2 on 2022-01-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0027_auto_20220130_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='financeAwareness.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
