# Generated by Django 3.2 on 2022-01-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0028_auto_20220130_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
