# Generated by Django 3.2 on 2022-01-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0029_auto_20220130_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Przychód'), ('expense', 'Wydatek'), ('planned', 'Zaplanowana'), ('recurring', 'Stała'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
