# Generated by Django 3.2 on 2022-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0032_tag_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='financeAwareness.Tag'),
        ),
    ]
