# Generated by Django 3.2 on 2022-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0033_auto_20220201_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='financeAwareness.Tag'),
        ),
    ]
