# Generated by Django 3.2 on 2022-02-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0036_auto_20220203_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reccuringType',
            field=models.CharField(blank=True, choices=[('month', 'Miesiąc'), ('quarter', 'Kwartał'), ('year', 'Rok'), ('week', 'tydzień')], max_length=20, null=True),
        ),
    ]
