# Generated by Django 3.2 on 2022-02-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAwareness', '0038_alter_transaction_reccuringtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reccuringType',
            new_name='reccuring_type',
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='is_planned',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
